# Generated by Django 3.1.2 on 2020-11-21 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='supplier',
            new_name='name',
        ),
    ]
