# Generated by Django 3.1.2 on 2020-11-21 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201120_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='supplier',
            new_name='supplier_name',
        ),
    ]
